### PR TITLE
feat: output warnings

### LINKED ISSUE #285: Ignore compiler warnings
Currently, `duck build:js` ignores warnings of compiling.
But we have a case that we want to get the warnings.
I have two options for this.

1. Prints warnings to stderr using `console.error` https://github.com/koba04/duck/commit/622e593384ea111c74956e2a4373664bc334bfd6
1. Add `--strict` option that treats any warnings as errors https://github.com/koba04/duck/commit/59238d90d6f21b2164a3b20a50665a74b30c0956

We could combine the options, which means that if `--strict` option is disabled, warnings are printed to stderr.

@teppeis Do you have any ideas for this issue?

### PR DESCRIPTION
**Pull request by teppeis**
fixes #285

### CODE REVIEW

**Comment by koba04** [comment]
@teppeis 
I've tried this PR locally and then have 2 questions.



1. Currently, the following output is always printed even if the compiling has no warning. I think the output should be filtered when the result has no warning.
Because the output has no meaning and lead to overlook warnings if we compile with many config files.
What do you think?

```
# <<config file path>>



0 error(s), 0 warning(s), 98.5% typed
```

2. when we use `duck build:js` instead of `duck build`, the warnings isn't printed. Is it intentional?

**Comment by teppeis** [comment]
@koba04 @pirosikick I've merged your PRs and fixed some issues. Please LGTM!

**Comment by teppeis** [comment]
Note: google-closure-compiler returns command line for each error but not for warning.
It's not consistent, but duck displays it only when error. Because I think the arguments are useful information for debugging.

**Comment by teppeis** [comment]
Pika CI has been in progress for 3 hours...

**Comment by teppeis** [comment]
@koba04 @pirosikick Sorry, your contributions are disappeared from commit logs when squashed...
I should have created a merge commit instead.

**Pull request merged**
